# name: py38
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - hdf5
  - zarr
  - pillow
  - scipy
  - ipykernel
  - numpy
  - pims
  - python
  - matplotlib
  - scikit-image
  - jpype1
  - tqdm
  - distributed
  - dask
  - ipywidgets
  - scikit-learn
  - pandas
  - seaborn

