[tool.poetry]
name = "pydecon"
version = "0.1.0"
description = ""
authors = ["Craig  <ctr26@ebi.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
scikit-image = "^0.18.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
